/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package com.xwiki.projectmanagement.openproject.script;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import org.xwiki.component.annotation.Component;
import org.xwiki.component.manager.ComponentLookupException;
import org.xwiki.rendering.syntax.Syntax;
import org.xwiki.script.service.ScriptService;
import org.xwiki.security.authorization.ContextualAuthorizationManager;
import org.xwiki.security.authorization.Right;

import com.xwiki.commons.document.MacroUtils;
import com.xwiki.projectmanagement.exception.AuthenticationException;
import com.xwiki.projectmanagement.exception.ProjectManagementException;
import com.xwiki.projectmanagement.exception.WorkItemRetrievalException;
import com.xwiki.projectmanagement.model.PaginatedResult;
import com.xwiki.projectmanagement.openproject.FilterBuilder;
import com.xwiki.projectmanagement.openproject.OpenProjectApiClient;
import com.xwiki.projectmanagement.openproject.config.OpenProjectConfiguration;
import com.xwiki.projectmanagement.openproject.config.OpenProjectConnection;
import com.xwiki.projectmanagement.openproject.internal.UserTokenChecker;
import com.xwiki.projectmanagement.openproject.internal.displayer.StylingSetupManager;
import com.xwiki.projectmanagement.openproject.model.WikiPageLink;

/**
 * @version $Id$
 * @since 1.0
 */
@Component
@Named("openproject")
@Singleton
public class OpenProjectScriptService implements ScriptService
{
    @Inject
    private OpenProjectConfiguration openProjectConfiguration;

    @Inject
    private StylingSetupManager stylingSetupManager;

    @Inject
    private ContextualAuthorizationManager authorizationManager;

    @Inject
    private MacroUtils macroUtils;

    @Inject
    private UserTokenChecker userTokenChecker;

    /**
     * Retrieves a list of available OpenProject connections.
     *
     * @return a list of {@code OpenProjectConnection} instances;
     */
    public List<Map<String, String>> getConnectionOptions() throws AuthenticationException
    {
        List<OpenProjectConnection> openProjectConnections = openProjectConfiguration.getOpenProjectConnections();

        List<Map<String, String>> options = new ArrayList<>();

        for (OpenProjectConnection openProjectConnection : openProjectConnections) {
            Map<String, String> option = new HashMap<>();
            option.put("name", openProjectConnection.getConnectionName());
            option.put("value", openProjectConnection.getConnectionName());
            options.add(option);
        }
        return options;
    }

    /**
     * @param instance the configured OpenProject connection.
     * @return the server url of the given OpenProject connection.
     * @since 1.2.0
     */
    public String getConnectionUrl(String instance)
    {
        OpenProjectConnection openProjectConnection = openProjectConfiguration.getConnection(instance);
        if (openProjectConnection == null) {
            return null;
        }
        return openProjectConnection.getServerURL();
    }

    /**
     * @param instanceName the name of the Open Project instance configuration.
     * @return whether the user was authorized to the configured Open Project instance or not.
     * @since 1.0-rc-3
     */
    public boolean isUserAuthorized(String instanceName)
    {
        String accessToken = openProjectConfiguration.getAccessTokenForConfiguration(instanceName);
        return accessToken != null;
    }

    /**
     * Generate the styling for the configured instances. Since this method will need to communicate with the configured
     * instances and make http requests, it should be run in a separate thread.
     */
    public void generateStyling() throws ProjectManagementException
    {
        if (!authorizationManager.hasAccess(Right.ADMIN)) {
            throw new ProjectManagementException(
                "The styles for the configured Open Project instances should be generated by an admin.");
        }
        stylingSetupManager.setupInstanceStyles();
    }

    /**
     *
     * @param instance the configured OpenProject instance against which the user should be authenticated.
     * @param syntax the syntax in which the message will be rendered.
     * @return a warning message rendered in the given syntax.
     * @throws ComponentLookupException if the syntax does not exist.
     * @since 1.2.0
     */
    public String getNotAuthorizedMessage(String instance, Syntax syntax) throws ComponentLookupException
    {
        return macroUtils.renderMacroContent(userTokenChecker.getWarningBlock(instance), syntax);
    }

    /**
     * @return a new instance of a filter builder that can be used to create OpenProject filters.
     * @since 1.2.0
     */
    public FilterBuilder getFilterBuilder()
    {
        return new FilterBuilder();
    }

    /**
     * @param instance the OP instance configuration that will be used.
     * @param page the number of the page.
     * @param pageSize the number of elements per page.
     * @param filters the OP rest filters.
     * @return a list of OpenProject wiki links - entities that represent wiki pages mentioned inside a work package.
     * @throws ProjectManagementException if some exception is thrown.
     * @since 1.2.0
     */
    public PaginatedResult<WikiPageLink> getMentioningWorkPackages(String instance, int page, int pageSize,
        String filters) throws ProjectManagementException
    {
        OpenProjectApiClient openProjectApiClient =
            openProjectConfiguration.getOpenProjectApiClient(instance);

        try {
            return openProjectApiClient.getPageLinks(page, pageSize, filters);
        } catch (WorkItemRetrievalException e) {
            // This means that the endpoint is not available. The UI should print a message informating the user
            // about that.
            if (e.getStatusCode() == 404) {
                return null;
            } else {
                throw e;
            }
        }
    }
}
