# ---------------------------------------------------------------------------
# See the NOTICE file distributed with this work for additional
# information regarding copyright ownership.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA, or see the FSF site: http://www.fsf.org.
# ---------------------------------------------------------------------------
# Calendar time interval
calendar.timeinterval.error=The minimum time cannot be later than the maximum time.
calendar.timeinterval.max.title=Max time
calendar.timeinterval.min.title=Min time
# CalendarViews enum
com.xwiki.projectmanagement.calendar.CalendarViews.agendaDay=Agenda Day
com.xwiki.projectmanagement.calendar.CalendarViews.agendaWeek=Agenda Week
com.xwiki.projectmanagement.calendar.CalendarViews.basicDay=Basic Day
com.xwiki.projectmanagement.calendar.CalendarViews.basicWeek=Basic Week
com.xwiki.projectmanagement.calendar.CalendarViews.month=Month
# WeekDays enum
com.xwiki.projectmanagement.calendar.WeekDays.FRIDAY=Friday
com.xwiki.projectmanagement.calendar.WeekDays.MONDAY=Monday
com.xwiki.projectmanagement.calendar.WeekDays.SATURDAY=Saturday
com.xwiki.projectmanagement.calendar.WeekDays.SUNDAY=Sunday
com.xwiki.projectmanagement.calendar.WeekDays.THURSDAY=Thursday
com.xwiki.projectmanagement.calendar.WeekDays.TUESDAY=Tuesday
com.xwiki.projectmanagement.calendar.WeekDays.WEDNESDAY=Wednesday
